
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn routes:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run streamlitPages/initial_page.py --server.port 8501
    volumes:
      - .:/app

  mlflow:
    build: .
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0 --port 5000
    volumes:
      - .:/app